version: '3.8'

services:
  app:
    container_name: 'meme-app_app'
    build: '.'
    volumes:
      - '.:/app:z'
    links:
      - 'redis:redis'
      - 'db:db'
  nginx:
    container_name: 'meme-app_nginx'
    image: nginx
    ports:
      - 8000:8000
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf:z'
      - '.:/app:z'
    links:
      - 'app:app'
    restart: always
  redis:
    container_name: 'meme-app_redis'
    image: redis
    restart: always
  db:
    container_name: 'meme-app_db'
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    restart: always
    ports:
      - '33061:3306'
